<? include('cabecera.php'); ?>


<div id="pagina_centrada">
    <div class="menu">
        <div id="nav-ppal">
            <nav id="nav-sec">
                <ul>
                    <li class="elemento_seleccionado"><a href="index.php" title="Home">Home</a></li>
                    <li class="elemento_no_selec"><a href="#">Especialidad</a>
                        <ul class='submenu'>
                            <li class="elemento_no_selec"><a href="#">Derecho mercantil</a></li>
                            <li class="elemento_no_selec"><a href="#">Derecho civil</a></li>
                            <li class="elemento_no_selec"><a href="#">Derecho contecioso-administrativo</a></li>
                            <li class="elemento_no_selec"><a href="#">Recursos</a></li>
                        </ul>
                    </li>
                    <li class="elemento_no_selec"><a href="#">Titular</a></li>
                    <li class="elemento_no_selec"><a href="#">Publicaciones</a></li>
                    <li class="elemento_no_selec"><a href="#">Libros</a>
                        <ul class='submenu submenu_grande'>
                            <li class="elemento_no_selec"><a href="#">Manual de Procuradores</a></li>
                            <li class="elemento_no_selec"><a href="#">Legislaci&oacute;n procesal <br>espa&ntilde;ola para procuradores</a></li>
                            <li class="elemento_no_selec"><a href="#">Tesis doctoral in&eacute;dita <br>Melqu&iacute;ades Alvarez</a></li>
                            <li class="elemento_no_selec"><a href="#">Melqu&iacute;ades Alvarez <br>discursos parlamentarios</a></li>
                            <li class="elemento_no_selec"><a href="#">Otros</a></li>
                        </ul>
                    </li>
                    <li class="elemento_no_selec"><a href="#">Docencia</a></li>
                    <li class="elemento_no_selec"><a href="#">Conferencias</a></li>
                    <li class="elemento_no_selec"><a href="#">Prensa</a>
                        <ul class='submenu'>
                            <li class="elemento_no_selec"><a href="#">Peri&oacute;dicos</a></li>
                            <li class="elemento_no_selec"><a href="#">Radio</a></li>
                            <li class="elemento_no_selec"><a href="#">Televisi&oacute;n</a></li>
                        </ul>
                    </li>
                    <li class="elemento_no_selec"><a href="#">Aviso legal</a>
                        <ul class='submenu'>
                            <li class="elemento_no_selec"><a href="#">Aviso legal</a></li>
                            <li class="elemento_no_selec"><a href="#">Politica de privacidad</a></li>
                        </ul>
                    </li>
                    <li class="elemento_no_selec"><a href="#">Contacto</a></li>
                </ul>
            </nav>
        </div>
    </div>

    <div id="contenido">
        <article class="articulo">
            <div class="estilo-contenido">

                <!-- Contenido principal -->
                <p><img class="centrado" title="home_main" src="images/estamos-trabajando.png" alt="construccion" width="260px" height="260px" />
                    <strong><center>Página en construcción</center></strong><br/>



                    <!-- contenido secundario-->
                <div id="subcontenido">
                    <p>Nuestro horario de oficina es desde las 9:00 hrs hasta las 20:00 hrs. <br>Fuera de este horario, puede contactar con nosotros en el tel&eacute;fono <br>+34 91 578 06 10.</p>
                </div>

            </div><!-- estilo-contenido -->
        </article>
    </div><!-- contenido -->
</div>

<? include('footer.php'); ?>
